name: chat_bubbles_with_time
description: Flutter chat bubble widgets, similar to Whatsapp and more shapes.
  Easy to use and implement chat bubbles.
version: 1.5.0
homepage: https://github.com/prahack/chat_bubbles

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  photo_view: ^0.14.0
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
